name: Rust & Cargo Build and Deploy for Innersource Library
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_TOKEN: ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}
  CARGO_REGISTRIES_INNERSOURCE_TOKEN: ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}
  CARGO_REGISTRIES_JFROGQUOTES_TOKEN: ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Cargo installation
        run: cargo --version

      # This step is helpful to prevent messing with different checksums being produced on the same semver
      - name: Preprocess Cargo.toml
        working-directory: jfrog_quotes
        run: |
            build_number=${{ github.run_number }}
            sed -i "s/^version = \"0.1.dev\"/version = \"0.1.${build_number}\"/" Cargo.toml

      - name: Build Library
        working-directory: jfrog_quotes
        run: cargo build --release --verbose

      - name: Publish Library To Artifactory
        working-directory: jfrog_quotes
        run: cargo publish --token "Bearer ${{ secrets.RUST_EXAMPLE_AUTHENTICATION_TOKEN }}"